/**
 * AI Variant Suggestion Route (Gemini BYOK)
 *
 * POST /api/ai/suggest-variants
 * Accepts a user-provided Gemini API key and routine context,
 * returns suggested routine variants generated by Gemini.
 */

import type { Request, Response } from 'express';
import type { RoutineVariant, RoutineStep } from '../../models/persistenceTypes';

interface SuggestVariantsRequest {
    routineId?: string;
    routineTitle: string;
    categoryId?: string;
    existingSteps: Array<{ title: string; instruction?: string; timerSeconds?: number }>;
    variantCount?: number;
    geminiApiKey: string;
}

/**
 * POST /api/ai/suggest-variants
 */
export async function postSuggestVariants(req: Request, res: Response): Promise<void> {
    try {
        const body = req.body as SuggestVariantsRequest;

        if (!body.geminiApiKey || typeof body.geminiApiKey !== 'string' || body.geminiApiKey.trim().length < 10) {
            res.status(400).json({
                error: { code: 'VALIDATION_ERROR', message: 'A valid Gemini API key is required' },
            });
            return;
        }

        if (!body.routineTitle || typeof body.routineTitle !== 'string' || body.routineTitle.trim().length === 0) {
            res.status(400).json({
                error: { code: 'VALIDATION_ERROR', message: 'Routine title is required' },
            });
            return;
        }

        const variantCount = Math.min(Math.max(body.variantCount || 2, 1), 4);
        const existingStepsText = body.existingSteps.length > 0
            ? body.existingSteps.map((s, i) => {
                let line = `${i + 1}. ${s.title}`;
                if (s.instruction) line += ` — ${s.instruction}`;
                if (s.timerSeconds) line += ` (${Math.floor(s.timerSeconds / 60)}:${(s.timerSeconds % 60).toString().padStart(2, '0')} timer)`;
                return line;
            }).join('\n')
            : '(No existing steps)';

        const prompt = `You are a wellness and productivity coach helping users create routine variants in a habit-tracking app.

The user has a routine called "${body.routineTitle}" with these current steps:
${existingStepsText}

Please suggest ${variantCount} variant(s) of this routine. Each variant should be a different intensity or duration (e.g., "Quick", "Standard", "Deep", "Weekend").

Respond ONLY with a valid JSON array. Each element must have this exact shape:
{
  "name": "Variant Name",
  "description": "Brief description of when to use this variant",
  "estimatedDurationMinutes": <number>,
  "steps": [
    {
      "title": "Step title",
      "instruction": "Optional instruction text",
      "timerSeconds": <optional number or null>
    }
  ]
}

Rules:
- Each variant must have 2-15 steps
- Variant names should be short (1-3 words)
- Descriptions should be 1 sentence
- estimatedDurationMinutes should be realistic
- timerSeconds is optional (use null if not needed)
- Steps should be practical and actionable
- Variants should meaningfully differ in scope, duration, or focus
- Do NOT wrap in markdown code blocks. Return raw JSON only.`;

        const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(body.geminiApiKey.trim())}`;

        const geminiResponse = await fetch(geminiUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                contents: [{ parts: [{ text: prompt }] }],
                generationConfig: {
                    temperature: 0.8,
                    maxOutputTokens: 4096,
                    // Disable thinking for structured JSON output
                    thinkingConfig: { thinkingBudget: 0 },
                },
            }),
        });

        if (!geminiResponse.ok) {
            const errorBody = await geminiResponse.text();
            console.error('[AI Variants] Gemini API error:', geminiResponse.status, errorBody);

            if (geminiResponse.status === 400 || geminiResponse.status === 403) {
                res.status(401).json({
                    error: {
                        code: 'GEMINI_AUTH_ERROR',
                        message: 'Invalid Gemini API key. Please check your key in Settings.',
                    },
                });
                return;
            }

            res.status(502).json({
                error: {
                    code: 'GEMINI_API_ERROR',
                    message: 'Failed to get response from Gemini. Please try again later.',
                },
            });
            return;
        }

        const geminiData = await geminiResponse.json() as {
            candidates?: Array<{ content?: { parts?: Array<{ text?: string; thought?: boolean }> } }>;
        };

        // Extract the output text (skip any "thought" parts from thinking models)
        const parts = geminiData?.candidates?.[0]?.content?.parts || [];
        const outputPart = parts.find(p => !p.thought && p.text) || parts[0];
        const rawText = outputPart?.text || '';

        // Parse the JSON from Gemini's response (strip markdown fences if present)
        let cleaned = rawText.trim();
        if (cleaned.startsWith('```')) {
            cleaned = cleaned.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '').trim();
        }

        let parsed: Array<{
            name: string;
            description?: string;
            estimatedDurationMinutes: number;
            steps: Array<{ title: string; instruction?: string; timerSeconds?: number | null }>;
        }>;

        try {
            parsed = JSON.parse(cleaned);
        } catch {
            console.error('[AI Variants] Failed to parse Gemini JSON:', cleaned.slice(0, 500));
            res.status(502).json({
                error: {
                    code: 'GEMINI_PARSE_ERROR',
                    message: 'Failed to parse AI response. Please try again.',
                },
            });
            return;
        }

        if (!Array.isArray(parsed) || parsed.length === 0) {
            res.status(502).json({
                error: {
                    code: 'GEMINI_EMPTY_RESPONSE',
                    message: 'AI returned no variants. Please try again.',
                },
            });
            return;
        }

        // Map to RoutineVariant shape (IDs will be generated client-side)
        const now = new Date().toISOString();
        const suggestedVariants: RoutineVariant[] = parsed.map((v, idx) => ({
            id: '', // Client will generate UUID
            name: String(v.name || `Variant ${idx + 1}`).slice(0, 50),
            description: v.description ? String(v.description).slice(0, 200) : undefined,
            estimatedDurationMinutes: typeof v.estimatedDurationMinutes === 'number' ? v.estimatedDurationMinutes : 10,
            sortOrder: idx,
            steps: (v.steps || []).slice(0, 50).map((s, sIdx): RoutineStep => ({
                id: '', // Client will generate UUID
                title: String(s.title || `Step ${sIdx + 1}`).slice(0, 100),
                instruction: s.instruction ? String(s.instruction).slice(0, 500) : undefined,
                timerSeconds: typeof s.timerSeconds === 'number' && s.timerSeconds > 0 ? s.timerSeconds : undefined,
            })),
            linkedHabitIds: [],
            isAiGenerated: true,
            createdAt: now,
            updatedAt: now,
        }));

        res.status(200).json({ suggestedVariants });
    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error';
        console.error('[AI Variants] Error:', errorMessage);
        res.status(500).json({
            error: {
                code: 'INTERNAL_SERVER_ERROR',
                message: 'Failed to suggest variants',
                details: process.env.NODE_ENV === 'development' ? errorMessage : undefined,
            },
        });
    }
}
