/**
 * HabitPotentialEvidence Repository
 * 
 * MongoDB data access layer for HabitPotentialEvidence entities.
 * Provides creation and query operations for potential habit evidence.
 * 
 * This repository manages "signals" that a user *might* have completed a habit,
 * usually generated by routine steps. These do not count as habit completion
 * until explicitly confirmed by the user.
 */

import { getDb } from '../lib/mongoClient';
import type { HabitPotentialEvidence } from '../../models/persistenceTypes';
import { MONGO_COLLECTIONS } from '../../models/persistenceTypes';
import { randomUUID } from 'crypto';

const COLLECTION_NAME = MONGO_COLLECTIONS.HABIT_POTENTIAL_EVIDENCE;

/**
 * Create a new potential evidence record.
 * 
 * @param evidence - Evidence data (excluding id)
 * @param userId - User ID to associate with the evidence
 * @returns Created evidence
 */
export async function createPotentialEvidence(
    evidence: Omit<HabitPotentialEvidence, 'id'>,
    userId: string
): Promise<HabitPotentialEvidence> {

    const db = await getDb();
    const collection = db.collection(COLLECTION_NAME);

    const id = randomUUID();

    const newEvidence: HabitPotentialEvidence = {
        ...evidence,
        id,
    };

    // Create document to store in MongoDB (includes userId)
    const document = {
        ...newEvidence,
        userId,
        // Add date index for faster querying by day
        date: evidence.date,
    };

    const result = await collection.insertOne(document);

    if (!result.acknowledged) {
        throw new Error('Failed to create potential evidence');
    }

    return newEvidence;
}

/**
 * Get potential evidence for a specific day and/or habit.
 * 
 * @param date - Date string (YYYY-MM-DD)
 * @param habitId - Optional Habit ID filter
 * @param userId - User ID
 * @returns Array of HabitPotentialEvidence
 */
export async function getPotentialEvidence(
    date: string,
    userId: string,
    habitId?: string
): Promise<HabitPotentialEvidence[]> {
    const db = await getDb();
    const collection = db.collection(COLLECTION_NAME);

    const query: any = {
        userId,
        date,
    };

    if (habitId) {
        query.habitId = habitId;
    }

    const documents = await collection
        .find(query)
        .sort({ timestamp: -1 }) // Newest first
        .toArray();

    return documents.map(doc => {
        const { _id, userId: _, ...entry } = doc;
        return entry as HabitPotentialEvidence;
    });
}

/**
 * Check if evidence already exists for a specific routine step execution on a specific day.
 * Used to de-duplicate signals if the user steps back and forth.
 * 
 * @param routineId - Routine ID
 * @param stepId - Step ID
 * @param date - Date string
 * @param userId - User ID
 * @returns boolean
 */
export async function evidenceExistsForStep(
    routineId: string,
    stepId: string,
    date: string,
    userId: string
): Promise<boolean> {
    const db = await getDb();
    const collection = db.collection(COLLECTION_NAME);

    const count = await collection.countDocuments({
        userId,
        routineId,
        stepId,
        date
    });

    return count > 0;
}
